#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export PAGER='bat'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{,s}bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

# Add Homebrew provide shell completions
# https://docs.brew.sh/Shell-Completion
FPATH="/opt/homebrew/share/zsh/site-functions:/Users/clive/.zsh/completion:${FPATH}"

# >>> JVM installed by coursier >>>
export JAVA_HOME="/Users/clive/Library/Caches/Coursier/arc/https/cdn.azul.com/zulu/bin/zulu17.40.19-ca-jdk17.0.6-macosx_aarch64.tar.gz/zulu17.40.19-ca-jdk17.0.6-macosx_aarch64"
# <<< JVM installed by coursier <<<
